### ISSUE TITLE
[documentation] consolidate essential text reading examples into `end-to-end-rest`

### ISSUE THREAD

**Issue by myedibleenso** [ml4ai/ASKEM-TA1-DockerVM#39]
@enoriega , as a step towards simplifying and consolidating our examples (#39), can you work on migrating whatever text reading examples in https://github.com/ml4ai/ASKEM-TA1-DockerVM you’re committing to maintaining to the `end-to-end-rest` subdir and modify such that they use the docker-compose file included there?

**Comment by enoriega** [comment]
@myedibleenso There is one existing at https://github.com/ml4ai/ASKEM-TA1-DockerVM/blob/main/end-to-end-rest/notebooks/text_reading/text_reading_pipeline.ipynb
Should I move it up one directory?

**Comment by myedibleenso** [comment]
No, that one is fine where it is.  How about `text-reading-rest` and `text-reading-batch`?

**Comment by enoriega** [comment]
They're abandoned, so I will delete them with a PR

**Comment by enoriega** [comment]
Fixed with #41
