### ISSUE TITLE
[equations] Generate AMR output for equation-based input

### ISSUE THREAD

**Issue by myedibleenso** [ml4ai/ASKEM-TA1-DockerVM#4]
In coordination with @Free-Quarks , add AMR service for output to `equations-rest` example.
```[tasklist]
### Tasks
- [ ] https://github.com/ml4ai/skema/issues/289
- [x] [Add notebook](https://github.com/ml4ai/ASKEM-TA1-DockerVM/blob/c2404523e7bb0a0af7f773ac95881bb8f1700da7/equations-rest/notebooks/eqn2amr.ipynb)
```

**Comment by myedibleenso** [comment]
Close to having this example in place.  See the following snippet ...

```python
r = requests.put(f"{BASE_URL}/models/PN", json=json.load(f))
r.json()

requests.delete(f"{BASE_URL}/models/{MODEL_ID}").text
```

**Comment by myedibleenso** [comment]
^to be added in the Code -> FN section following the existing subsections: https://github.com/ml4ai/ASKEM-TA1-DockerVM/blob/main/end-to-end-rest/notebooks/e2e.ipynb

**Comment by Free-Quarks** [comment]
> Close to having this example in place. See the following snippet ...
> 
> ```python
> r = requests.put(f"{BASE_URL}/models/PN", json=json.load(f))
> r.json()
> 
> requests.delete(f"{BASE_URL}/models/{MODEL_ID}").text
> ```

Just a reminder that you don't need to also call the delete request, the put request cleans up after itself. The delete is a mostly internal endpoint at this point.

**Comment by myedibleenso** [comment]
@Free-Quarks , are there expectations we need to keep in mind about the pMML that you take as input?

**Comment by Free-Quarks** [comment]
For the eqn2amr endpoints, not really. Just a vector of mathml strings, each string being one equation of the system of equations. 

We don't have complete coverage over everything that can popup in pMML, but when it comes to the standard first order linear differential equations of our domain, it should be very good coverage.

**Comment by myedibleenso** [comment]
initial version completed during the hackathon.
