### ISSUE TITLE
[code2fn] Example notebook in `end-to-end-rest` for comment extraction

### ISSUE THREAD

**Issue by myedibleenso** [ml4ai/ASKEM-TA1-DockerVM#7]
Consulting with @adarshp , add an example notebook to `code2fn-rest` subdir that demonstrates how to call the comment extraction service from `lumai/askem-skema-rs`.

**Comment by myedibleenso** [comment]
@jastier , please coordinate with @vincentraymond-ua on this.

**Comment by myedibleenso** [comment]
@adarshp , is there a REST API in Rust for extracting comments?

**Comment by adarshp** [comment]
@myedibleenso  - yes, it's the `/get_comments` endpoint in the skema-rs service.

**Comment by adarshp** [comment]
Looks like it currently assumes that the source code being sent is Python (https://github.com/ml4ai/skema/blob/main/skema/skema-rs/skema/src/services/comment_extraction.rs). I can update it to handle Fortran and C/C++.

**Comment by myedibleenso** [comment]
Thanks, @adarshp !

**Comment by myedibleenso** [comment]
Complete (see e2e.ipynb)
